# -*- coding: utf-8 -*-
"""execution_SPARQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D1B7mAm2IdqEFbdOKIRaQx7pQhLNWSGP
"""

import requests
import time
from statistics import mean

ENDPOINT = "http://93.115.20.167:8890/sparql"
QUERY_FILE = "queries.txt"
RUNS = 5
BATCH_SIZE = 20


def load_queries(file_path):
    queries = {}
    current_name = None
    buffer = []

    with open(file_path, "r") as f:
        for line in f:
            if line.startswith("#") :
                if current_name:
                    queries[current_name] = "".join(buffer).strip()
                    buffer = []
                current_name = line.strip("# \n")
            else:
                buffer.append(line)

        if current_name:
            queries[current_name] = "".join(buffer).strip()

    return queries


def run_query(query):
    params = {
        "query": query,
        "format": "application/sparql-results+json"
    }

    start = time.perf_counter()
    r = requests.get(ENDPOINT, params=params)
    end = time.perf_counter()

    elapsed = end - start

    result_count = None
    if r.status_code == 200:
        try:
            data = r.json()
            result_count = len(data["results"]["bindings"])
        except:
            pass

    return elapsed, r.status_code, result_count


queries = load_queries(QUERY_FILE)

results = {}
all_times = []

batch_times = []
query_counter = 0
batch_id = 1


for name, query in queries.items():

    print(f"\nRunning {name}")
    times = []

    for i in range(RUNS):

        t, status, size = run_query(query)
        times.append(t)
        all_times.append(t)
        batch_times.append(t)

        print(
            f"run {i+1} | time={t:.3f}s | status={status} | results={size}"
        )

    results[name] = {
        "avg": mean(times),
        "min": min(times),
        "max": max(times)
    }

    query_counter += 1

    # ---- batch summary every 20 queries ----
    if query_counter % BATCH_SIZE == 0:

        print("\n===== BATCH SUMMARY =====")
        print(f"Batch {batch_id} (queries {query_counter-BATCH_SIZE+1}-{query_counter})")

        print(
            f"avg={mean(batch_times):.3f}s "
            f"min={min(batch_times):.3f}s "
            f"max={max(batch_times):.3f}s"
        )

        batch_times = []
        batch_id += 1


# ---- FINAL SUMMARY ----
print("\n===== FINAL BENCHMARK SUMMARY =====")

for q, stats in results.items():
    print(
        f"{q}: avg={stats['avg']:.3f}s "
        f"min={stats['min']:.3f}s "
        f"max={stats['max']:.3f}s"
    )

print("\n===== GLOBAL STATS =====")

print(
    f"overall avg={mean(all_times):.3f}s "
    f"min={min(all_times):.3f}s "
    f"max={max(all_times):.3f}s "
    f"total queries={len(results)}"
)

